version: "3.9"

networks:
  internal:
    driver: bridge

services:
  # 🗄️ Auth Service DB
  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    ports:
      - "5434:5432"
    env_file:
      - ./auth-service-db.env
    networks:
      - internal

  # 🗄️ Patient Service DB
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5433:5432"
    env_file:
      - ./patient-service-db.env
    networks:
      - internal

  # 🔑 Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4005:8080"
    env_file:
      - ./auth-service.env
    depends_on:
      - auth-service-db
    networks:
      - internal

  # 🏥 Patient Service
  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "4000:8080"
    env_file:
      - ./patient-service.env
    depends_on:
      - patient-service-db
      - billing-service
      - kafka
    networks:
      - internal

  # 💳 Billing Service
  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "4001:8080"
      - "9001:9001"   # gRPC port
    env_file:
      - ./billing-service.env
    networks:
      - internal

  # 📊 Analytics Service
  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "4002:8080"
    env_file:
      - ./analytics-service.env
    depends_on:
      - kafka
    networks:
      - internal

  # 🌐 API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "4004:8080"
    env_file:
      - ./api-gateway.env
    depends_on:
      - auth-service
      - patient-service
      - billing-service
      - analytics-service
    networks:
      - internal

  # 📡 Kafka (single node)
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092" 
      - "9094:9094" # external access
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    networks:
      - internal
